const express = require('express');
const cors = require('cors');
const authRoutes = require('./routes/auth');
const landingRoutes = require('./routes/landing');
const dashboardRoutes = require('./routes/dashboard');
const commissionRoutes = require('./routes/commission');
const payoutRoutes = require('./routes/payouts');
const linkRoutes = require('./routes/link');
const referralRoutes = require('./routes/referrals');
const userRoutes = require('./routes/users');
const quoteRoutes = require('./routes/quotes');
const onboardingRoutes = require('./routes/onboarding');
const notificationRoutes = require('./routes/notification');
const agencyRoutes = require('./routes/agency');
const employeeRoutes = require('./routes/employee');
const affiliateRoutes = require('./routes/affiliates');
const jobRoutes = require('./routes/jobs');
const analyticsRoutes = require('./routes/analytics');
const matchmakingRoutes = require('./routes/matchmaking');
const contractRoutes = require('./routes/contracts');
const clientRoutes = require('./routes/clients');
const securityRoutes = require('./routes/security');
const feedbackRoutes = require('./routes/feedback');
const feedbackSystemRoutes = require('./routes/feedbackSystem');
const investorFeedbackRoutes = require('./routes/investorFeedback');
const volunteerFeedbackRoutes = require('./routes/volunteerFeedback');
const financialRoutes = require('./routes/financial');
const financialTransactionRoutes = require('./routes/financialTransactions');
const trainingRoutes = require('./routes/training');
const dataProtectionRoutes = require('./routes/dataProtection');
const analyticsRoutes = require('./routes/analytics');
const agencyAnalyticsRoutes = require('./routes/agencyAnalytics');
const aiAnalyticsRoutes = require('./routes/aiAnalytics');
const classroomAnalyticsRoutes = require('./routes/classroomAnalytics');
const disputeAnalyticsRoutes = require('./routes/disputeAnalytics');
const educationAnalyticsRoutes = require('./routes/educationAnalytics');
const financialAnalyticsRoutes = require('./routes/financialAnalytics');
const employmentAnalyticsRoutes = require('./routes/employmentAnalytics');
const financialForecastingRoutes = require('./routes/financialForecasting');
const freelanceAnalyticsRoutes = require('./routes/freelanceAnalytics');
const gigAnalyticsRoutes = require('./routes/gigAnalytics');
const messageAnalyticsRoutes = require('./routes/messageAnalytics');
const realTimeMlAnalyticsRoutes = require('./routes/realTimeMlAnalytics');
const podcastAnalyticsRoutes = require('./routes/podcastAnalytics');
const workspaceAnalyticsRoutes = require('./routes/workspaceAnalytics');
const sentimentAnalysisRoutes = require('./routes/sentimentAnalysis');
const podcastAnalyticsRoutes = require('./routes/podcastAnalytics');
const serviceProviderAnalyticsRoutes = require('./routes/serviceProviderAnalytics');
const userAnalyticsRoutes = require('./routes/userAnalytics');
const webinarAnalyticsRoutes = require('./routes/webinarAnalytics');
const workspaceAnalyticsRoutes = require('./routes/workspaceAnalytics');
const realTimeAnalyticsRoutes = require('./routes/realTimeAnalytics');
const liveFeedAnalyticsRoutes = require('./routes/liveFeedAnalytics');
const mlAnalyticsRoutes = require('./routes/mlAnalytics');
const enhancedUserExperienceMLRoutes = require('./routes/enhancedUserExperienceML');
const operationalEfficiencySecurityMlRoutes = require('./routes/operationalEfficiencySecurityMl');
const predictiveMlRoutes = require('./routes/predictiveAnalyticsForecastingML');
const personalizedLearningRoutes = require('./routes/personalizedLearning');
const contentDiscoveryRoutes = require('./routes/contentDiscovery');
const communityEngagementMLRoutes = require('./routes/communityEngagementML');
const mlSecurityRoutes = require('./routes/mlSecurity');
const infrastructureOptimizationRoutes = require('./routes/infrastructureOptimization');
const courseRoutes = require('./routes/courses');
const aiEnhancedLearningRoutes = require('./routes/aiEnhancedLearningDevelopment');
const userFeedbackAdjustmentRoutes = require('./routes/userFeedbackAdjustment');
const integrationRoutes = require('./routes/integration');
const sessionRoutes = require('./routes/sessions');
const infrastructureOptimizationRoutes = require('./routes/infrastructureOptimization');
const externalDataMLRoutes = require('./routes/externalDataML');
const machineLearningRoutes = require('./routes/machineLearning');
const transformersGpt2Routes = require('./routes/transformersGpt2');
const trendRoutes = require('./routes/trends');
const sessionRoutes = require('./routes/sessions');
const profilesRoutes = require('./routes/profiles');
const matchingEngineRoutes = require('./routes/matchingEngine');
const additionalFeaturesRoutes = require('./routes/additionalFeatures');
const mentorshipManagementRoutes = require('./routes/mentorshipManagement');
const eventRoutes = require('./routes/events');
const participantRoutes = require('./routes/participants');
const matchingSystemRoutes = require('./routes/matchingSystem');
const matchingRoutes = require('./routes/matching');
const communicationRoutes = require('./routes/communicationTools');
const communicationsRoutes = require('./routes/communications');
const goalRoutes = require('./routes/goals');
const milestoneRoutes = require('./routes/milestones');
const progressRoutes = require('./routes/progress');
const achievementRoutes = require('./routes/achievements');
const skillRoutes = require('./routes/skills');
const gamificationRoutes = require('./routes/gamification');
const portfolioRoutes = require('./routes/portfolio');
const reviewRoutes = require('./routes/reviews');
const resourceRoutes = require('./routes/resources');
const assessmentRoutes = require('./routes/assessments');
const certificateRoutes = require('./routes/certificates');
const learningPathRoutes = require('./routes/paths');
const socialRoutes = require('./routes/social');
const communityRoutes = require('./routes/community');
const projectRoutes = require('./routes/projects');
const opportunityRoutes = require('./routes/opportunities');
const expertAccessRoutes = require('./routes/expertAccess');
const investorGroupRoutes = require('./routes/investors');
const volunteerRoutes = require('./routes/volunteers');
const applicationRoutes = require('./routes/applications');
const campaignRoutes = require('./routes/campaigns');
const projectManagementRoutes = require('./routes/projectManagement');
const successStoryRoutes = require('./routes/successStories');
const thirdPartyApiRoutes = require('./routes/thirdPartyApis');
const app = express();
app.use(cors());
app.use(express.json());

// Mount routes. The parent application may prefix these with "/api"
// when integrating the backend.
app.use('/auth', authRoutes);
app.use('/landing', landingRoutes);
app.use('/affiliates', dashboardRoutes);
app.use('/commissions', commissionRoutes);
app.use('/payouts', payoutRoutes);
app.use('/affiliates', linkRoutes);
app.use('/referrals', referralRoutes);
app.use('/users', userRoutes);
app.use('/quotes', quoteRoutes);
app.use('/affiliates', onboardingRoutes);
app.use('/agency', agencyRoutes);
app.use('/hr', employeeRoutes);
app.use('/affiliates', affiliateRoutes);
app.use('/agency/jobs', jobRoutes);
app.use('/agency', jobRoutes);
app.use('/agency', analyticsRoutes);
app.use('/agency', matchmakingRoutes);
app.use('/contracts', contractRoutes);
app.use('/agency', clientRoutes);
app.use('/security', securityRoutes);
app.use('/agency', feedbackRoutes);
app.use('/feedback', feedbackSystemRoutes);
app.use('/feedback', investorFeedbackRoutes);
app.use('/feedback', volunteerFeedbackRoutes);
app.use('/agency', financialRoutes);
app.use('/financial', financialTransactionRoutes);
app.use('/hr/training', trainingRoutes);
app.use('/training', trainingRoutes);
app.use('/analytics', analyticsRoutes);
app.use('/analytics', agencyAnalyticsRoutes);
app.use('/analytics', realTimeAnalyticsRoutes);
app.use('/ai-analytics', aiAnalyticsRoutes);
app.use('/classroom-analytics', classroomAnalyticsRoutes);
app.use('/analytics/disputes', disputeAnalyticsRoutes);
app.use('/education-analytics', educationAnalyticsRoutes);
app.use('/financial-analytics', financialAnalyticsRoutes);
app.use('/agency/:agencyId/payments', paymentRoutes);
app.use('/analytics/employment', employmentAnalyticsRoutes);
app.use('/forecasting', financialForecastingRoutes);
app.use('/analytics/freelance', freelanceAnalyticsRoutes);
app.use('/analytics/gig', gigAnalyticsRoutes);
app.use('/analytics/messages', messageAnalyticsRoutes);
app.use('/ml/real-time', realTimeMlAnalyticsRoutes);
app.use('/podcast-analytics', podcastAnalyticsRoutes);
app.use('/analytics/workspace', workspaceAnalyticsRoutes);
app.use('/sentiment', sentimentAnalysisRoutes);
app.use('/podcast-analytics', podcastAnalyticsRoutes);
app.use('/service-providers', serviceProviderAnalyticsRoutes);
app.use('/analytics/user', userAnalyticsRoutes);
app.use('/webinar-analytics', webinarAnalyticsRoutes);
app.use('/analytics/workspace', workspaceAnalyticsRoutes);
app.use('/analytics/live-feed', liveFeedAnalyticsRoutes);
app.use('/ml', mlAnalyticsRoutes);
app.use('/ml', enhancedUserExperienceMLRoutes);
app.use('/ml', operationalEfficiencySecurityMlRoutes);
app.use('/ml', predictiveMlRoutes);
app.use('/ml', personalizedLearningRoutes);
app.use('/ml', contentDiscoveryRoutes);
app.use('/ml/community', communityEngagementMLRoutes);
app.use('/ml/security', mlSecurityRoutes);
app.use('/ml', infrastructureOptimizationRoutes);
app.use('/courses', courseRoutes);
app.use('/ml/learning', aiEnhancedLearningRoutes);
app.use('/', userFeedbackAdjustmentRoutes);
app.use('/integration', integrationRoutes);
app.use('/sessions', sessionRoutes);
app.use('/ml', infrastructureOptimizationRoutes);
app.use('/', externalDataMLRoutes);
app.use('/ml', machineLearningRoutes);
app.use('/ml/transformers', transformersGpt2Routes);
app.use('/trends', trendRoutes);
app.use('/sessions', sessionRoutes);
app.use('/profiles', profilesRoutes);
app.use('/matching', matchingEngineRoutes);
app.use('/mentorship', additionalFeaturesRoutes);
app.use('/management', mentorshipManagementRoutes);
app.use('/events', eventRoutes);
app.use('/participants', participantRoutes);
app.use('/matching', matchingSystemRoutes);
app.use('/matches', matchingRoutes);
app.use('/communication', communicationRoutes);
app.use('/communications', communicationsRoutes);
app.use('/progress', progressRoutes);
app.use('/achievements', achievementRoutes);
app.use('/skills', skillRoutes);
app.use('/portfolio', portfolioRoutes);
app.use('/reviews', reviewRoutes);
app.use('/paths', learningPathRoutes);
app.use('/social', socialRoutes);
app.use('/community', communityRoutes);
app.use('/projects', projectRoutes);
app.use('/opportunities', opportunityRoutes);
app.use('/volunteers', volunteerRoutes);
app.use('/campaigns', campaignRoutes);
app.use('/goals', goalRoutes);
app.use('/milestones', milestoneRoutes);
app.use('/gamification', gamificationRoutes);
app.use('/', resourceRoutes);
app.use('/assessments', assessmentRoutes);
app.use('/certificates', certificateRoutes);
app.use('/experts', expertAccessRoutes);
app.use('/investors', investorGroupRoutes);
app.use('/applications', applicationRoutes);
app.use('/success', successStoryRoutes);
app.use('/affiliates/notifications', notificationRoutes);
app.use('/workspace', projectManagementRoutes);
app.use('/third-party', thirdPartyApiRoutes);

const port = process.env.PORT || 5000;
if (require.main === module) {
  app.listen(port, () => console.log(`Server running on port ${port}`));
}

module.exports = app;
