-- Central database schema for Workhouse
-- Aggregates all module schemas

\i additional_features.sql
\i agency.sql
\i ai_analytics.sql
\i ai_enhanced_learning_development.sql
\i analytics.sql
\i applications.sql
\i assessment.sql
\i campaigns.sql
\i commission.sql
\i communication.sql
\i communication_tools.sql
\i community.sql
\i community_engagement_ml.sql
\i community_subscription.sql
\i config.sql
\i content.sql
\i content_discovery.sql
\i content_library.sql
\i courses.sql
\i dashboard.sql
\i education_schedule.sql
\i employee.sql
\i enhanced_user_experience_ml.sql
\i event_controller.sql
\i events.sql
\i expert_access.sql
\i externalDataML.sql
\i feedback_system.sql
\i financial_forecasting.sql
\i financial_transactions.sql
\i freelance_analytics.sql
\i gamification.sql
\i gig_analytics.sql
\i gigs.sql
\i goals.sql
\i infrastructureOptimization.sql
\i integration.sql
\i interviews.sql
\i investor_feedback.sql
\i investor_groups.sql
\i investor_profiles.sql
\i landing_content.sql
\i learning_paths.sql
\i link.sql
\i live_feed.sql
\i live_feed_analytics.sql
\i machine_learning.sql
\i matching.sql
\i matching_engine.sql
\i matching_system.sql
\i mentorship_program_management.sql
\i messageAnalytics.sql
\i milestones.sql
\i ml_analytics.sql
\i ml_security.sql
\i network_profiles.sql
\i notificationSettings.sql
\i notifications.sql
\i operational_efficiency_security_ml.sql
\i opportunities.sql
\i participant.sql
\i payouts.sql
\i personalized_learning.sql
\i podcastAnalytics.sql
\i portfolio.sql
\i predictive_analytics_forecasting_ml.sql
\i products.sql
\i profiles.sql
\i progress_tracking.sql
\i project_management.sql
\i projects.sql
\i real_time_analytics.sql
\i real_time_ml_analytics.sql
\i referrals.sql
\i resources.sql
\i resume.sql
\i reviews.sql
\i sentiment_analysis.sql
\i service_provider_analytics.sql
\i sessions.sql
\i social_learning.sql
\i success_stories.sql
\i system_settings.sql
\i training.sql
\i transformers_gpt2.sql
\i userAnalytics.sql
\i user_feedback_adjustment.sql
\i user_progress.sql
\i users.sql
\i volunteer_analytics.sql
\i volunteer_feedback.sql
\i volunteering_dashboard.sql
\i volunteers.sql
\i webinar_analytics.sql
\i workspace_analytics.sql
