CREATE TABLE IF NOT EXISTS projects (
  id UUID PRIMARY KEY,
  path_id UUID,
  owner_id VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  link TEXT,
  collaborators JSONB,
  external BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
